name: Build CodeWalker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install NuGet dependencies
      run: nuget restore CodeWalker.sln

    - name: Build solution
      run: msbuild CodeWalker.sln /p:Configuration=Release /p:Platform="x64"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CodeWalker-Build
        path: |
          **/bin/x64/Release/*
